branches:
  except:
    - /^v2017/
language: python
sudo: required
services:
  - docker
notifications:
  email: false
python:
  - "3.6"
before_script:
  - docker build -t brochat-bot .
  - pip3 install pylint
script:
  - pylint -E --ignored-modules=distutils objs/* cogs/* *.py
  - python3 objs/duel_item.py
  - python3 main.py

